#' Build a cleaned eDNA sampling dataset from the raw eDNA-for-MPAs directory
#'
#' This function recursively scans the `eDNA-for-MPAs/data/` directory to
#' locate all CSV files containing `"GOTeDNA"` in their file name or path.
#' Files are grouped by cruise mission, metadata and data files are paired,
#' naming inconsistencies are corrected, and a unified table of sample-level
#' information is produced.
#'
#' The function performs several formatting corrections, including:
#' - resolving inconsistent `materialSampleID` naming (e.g., `X`, `_`, `-`)
#' - handling metadata files with different column name conventions
#' - resolving location name inconsistencies (e.g., `ESI`, `SAB`)
#' - extracting sample dates, coordinates, richness, and method type
#' - correcting positive longitudes by flipping sign
#'
#' The final result is a single cleaned data frame with one row per sample.
#'
#' @details
#' The function assumes the following:
#' - The directory `../eDNA-for-MPAs/data/` exists and contains cruise folders.
#' - Metadata files contain either `materialSampleID`, `SampleID`, or `eDNA_Tube`.
#' - Species columns in data files may be named `Species`, `species`, or `V6`.
#' - Latitude/longitude may be stored as `decimalLatitude`/`decimalLongitude`
#'   or `Lat`/`Long`.
#'
#' The function prints progress messages (`i`, `j`, `k`, `l`)
#'
#' @param token A personal access token to allow downloading from Github
#' generated by going here: https://github.com/settings/tokens and
#' clicking 'Generate New Token'
#' @importFrom httr GET add_headers
#' @importFrom jsonlite fromJSON
#'
#' @return
#' A data frame containing:
#' \describe{
#'   \item{ID}{Sample identifier}
#'   \item{date}{Sampling date (class `Date`)}
#'   \item{latitude}{Sample latitude}
#'   \item{longitude}{Sample longitude (corrected to negative values)}
#'   \item{species_richness}{Count of unique species detected in the sample}
#'   \item{method}{eDNA sampling method inferred from folder structure}
#'   \item{location}{Sampling location identifier}
#'   \item{year}{Extracted sampling year}
#' }
#'
#' @examples
#' \dontrun{
#'   df <- data_eDNA(token='ghp_12345')
#'
#'   # Quick map preview
#'   leaflet::leaflet(df) %>%
#'     leaflet::addTiles() %>%
#'     leaflet::addCircleMarkers(
#'       lat = ~latitude,
#'       lng = ~longitude,
#'       popup = paste("Lat:", df$latitude, "<br>Lon:", df$longitude)
#'     )
#' }
#'
#' @export
data_eDNA <- function(token=NULL) {

  if (is.null(token)) {
    stop("Must provide a GitHub token to proceed.")
  }
  root <- 'https://github.com/NickJeff13/eDNA-for-MPAs/tree/master/data'

  api_url <- "https://api.github.com/repos/NickJeff13/eDNA-for-MPAs/contents/data"

  res <- httr::GET(
    api_url,
    httr::add_headers(Authorization = paste("token", token))
  )

  files <- jsonlite::fromJSON(content(res, "text"), flatten = TRUE)


  ### START NEW

  dirs <- files[which(files$type == 'dir'),] ## All of the directories in the repository

  ## Now we need to look at any files that that start with "GOTeDNA.*\\.csv$" - > NJ: Is this needed?
  get_gotedna_files <- function(url, token, depth = 1) {

    message("Currently at depth ", depth)

    res <- httr::GET(
      url,
      httr::add_headers(Authorization = paste("token", token))
    )

    items <- jsonlite::fromJSON(
      httr::content(res, "text"),
      flatten = TRUE
    )

    out <- c()

    for (i in seq_len(nrow(items))) {

      if (items$type[i] == "file" &&
          grepl("GOTeDNA.*\\.csv$", items$name[i], ignore.case = TRUE)) {

        out <- c(out, items$download_url[i])

      }

      if (items$type[i] == "dir") {

        message(
          paste0(
            strrep("  ", depth - 1),
            "Entering depth ", depth + 1,
            ": ", items$name[i]
          )
        )

        out <- c(
          out,
          get_gotedna_files(
            items$url[i],
            token,
            depth = depth + 1
          )
        )
      }
    }

    out
  }

  eDNA_csv <- get_gotedna_files(api_url, token)

  paths <- sub(".*data/", "", eDNA_csv)


  if (substr(paths[1], 1, 1) == "/") {
    paths <- substr(paths, 2, nchar(paths))
  }
  cruise <- sub("/.*", "", paths)
  grouped <- split(eDNA_csv, cruise) ## GROUPED BY CRUISE (BASED ON NAMING CONVENTION)


  big_df <- list()
  counter <- 1


  for (i in seq_along(grouped)) { # GROUP BY CRUISE MISSION
    message("i= ", i, " with cruise mission = ", names(grouped[i]))

    METADATA <- grouped[[i]][which(grepl("Metadata", grouped[[i]], ignore.case=TRUE))]

    DATA <- grouped[[i]][which(!grepl("Metadata", grouped[[i]], ignore.case=TRUE))]

    location <- sub(".*data/[^/]+/([^/]+)/.*", "\\1", METADATA)

    if (any(grepl("GOTeDNA", location, ignore.case=TRUE))) {
      message("Bad location for ", i)
      # FORMATTED INCORRECT (NJ)
      bad_location <- which(grepl("GOTeDNA", location, ignore.case=TRUE))

      location_options <- c("ESI", "SAB")

      hits <- location_options[ sapply(location_options, function(x)
        grepl(x, location[bad_location], ignore.case = TRUE)
      ) ]

      if (length(hits) == 0) {
        # COULD NOT FIND LOCATION NAME IN METADATA, NOW LOOKING IN DATA NAME
        hits <- location_options[ sapply(location_options, function(x)
          grepl(x, DATA[bad_location], ignore.case = TRUE)
        ) ]

        if (length(hits) == 0) {

          if (names(grouped[i]) == '2025RVsurvey') {
            location <- '2025RVsurvey'
          } else {
          stop("There was a new location added, and formatting is incorrect.")
          }
        }
      }
      if (!(names(grouped[i]) == '2025RVsurvey')) {
      location[bad_location] <- hits
      }

    }

    for (j in seq_along(location)) { # CYCLE THROUGH ALL LOCATIONS ON CRUISE MISSION
      message("j= ", j, " with location = ", location[j])
      keepj <- which(grepl(location[j], DATA, ignore.case=TRUE)) ## ONLY LOOKING AT DATA FROM ONE LOCATION

      for (k in seq_along(keepj)) { # CYCLE THROUGH ALL SAMPLE TYPES AT EACH LOCATION FOR EACH MISSION

        ## FIXME: SHOULD LOOK INTO THIS
        message("k= ", k, " which is all sample types at each location for each mission (e.g. 16S)")

        name_of_data <- DATA[keepj][k]
        data <- read.csv(name_of_data)
        metadata <- read.csv(METADATA[j])

        if (!("materialSampleID" %in% names(metadata))) {
          # NOT CONSISTENT (NJ) - METADATA FILES USUALLY MATERIALSAMPLEID
          names(metadata)[which(names(metadata) == "SampleID")] <- "materialSampleID"
        }
        metadata$materialSampleID <- gsub("-", ".", metadata$materialSampleID)
        # ABOVE NOT CONSISTENT (NJ) - SOMETIMES MATERIALSAMPLEID _ AND SOMETIMES .


        HIT_IDs <- names(data)[which(names(data) %in% metadata$materialSampleID)]

        if (length(HIT_IDs) == 0) {
          message("Naming convention change")
          names(data) <- sub("^X", "", names(data)) # Sometimes there are leading X's
          HIT_IDs <- names(data)[which(names(data) %in% metadata$materialSampleID)]

        }

        if (length(HIT_IDs) == 0) {
          message("Naming convention change")
          message("Special case for i = 4, j=1,k=1 using both materialSampleID and eDNATube. Not consistent NJ")

          metadata$materialSampleID <- gsub("_", ".", metadata$materialSampleID)
          metadata$eDNA_Tube <- gsub("_", ".", metadata$eDNA_Tube)

          metadata$materialSampleID[which(!(grepl("AZMP", metadata$materialSampleID)))] <- metadata$eDNA_Tube[which(!(grepl("AZMP", metadata$materialSampleID)))]

          HIT_IDs <- names(data)[which(names(data) %in% metadata$materialSampleID)]
        }

        ## MAKING A SAFETY CHECK THAT ENSURES ANY DATA THAT DOES NOT HAVE METADATA IS ALL 0
        missing_samples <- names(data)[
          grepl("sample", names(data), ignore.case = TRUE) &
            !names(data) %in% metadata$materialSampleID &
            vapply(data, function(x) !all(x == 0, na.rm = TRUE), logical(1))
        ]

        if (length(missing_samples) > 0) {
          if (!(i == 1)) {
            browser()

            ## TESTING
            name_of_data
            METADATA[j]
            names(data)[!(which(names(data) %in% metadata$materialSampleID))]
            uniques <- lapply(missing_samples, function(x) unique(data[[x]]))
            names(uniques) <- missing_samples
            uniques


            stop("There is a dataset that does not have an associated metadata and is not all 0s. This is for i = ", i, " j = ",j, " k = ", k)
          }
        }




        df <- data.frame(ID= HIT_IDs,
                         date= as.Date(rep(NA, length(HIT_IDs))),
                         latitude=NA,
                         longitude=NA,
                         species_richness=NA,
                         method=NA,
                         location=NA,
                         species=NA,
                         abundance=NA)

        if (names(grouped[i]) == "2025RVsurvey") {
          df$location <- metadata$MPA[which(metadata$materialSampleID %in% HIT_IDs)]
        }


        for (l in seq_along(df$ID)) { ## CYCLE THROUGH EACH SAMPLE FOR EACH SAMPLE TYPE
          message("l= ", l)
          keep <- which(metadata$materialSampleID == df$ID[l])

          if (!(length(keep) == 0)) {

            df$date[l] <- as.Date(metadata$eventDate[keep], "%m/%d/%Y")

            # DATE NOT CONSISTENT, NJ

            if (is.na(df$date[l])) {
              is_date_format <- function(x, format) {
                !is.na(as.Date(x, format = format))
              }

              if (is_date_format(metadata$eventDate[keep], "%b %d %Y")) {
                #message("This is browser 1")
                #browser(1)
                # Handing "Aug 6 2022" date.
                df$date[l] <-as.Date(metadata$eventDate[keep], format = "%b %d %Y")
                df$date[l] <- gsub("-", "/", df$date[l])

              } else if (metadata$eventDate[keep] == "") {
                #Find the one before it that is not ""
                # if (k == 2 && j == 2) {
                # browser()
                # }
                date_of_interest <- metadata$eventDate[max(which(metadata$eventDate[1:(keep-1)] != ""))]
                df$date[l] <- as.Date(date_of_interest, format = "%m/%d/%Y")
                df$date[l] <- gsub("-", "/", df$date[l])

              } else if (grepl("^[A-Za-z]{3}-\\d{2}$", metadata$eventDate[keep])) {

                assigned_year <-  unique(stringr::str_extract(DATA, "\\d{4}"))

                df$date[l] <- as.Date(paste0(metadata$eventDate[keep], "-", assigned_year), format = "%b-%d-%Y")


              } else {
                message("This is browser 2")

                browser(2)
              }
            }

            if ("decimalLatitude" %in% names(metadata)) {
              df$latitude[l] <- metadata$decimalLatitude[keep]
              df$longitude[l] <- metadata$decimalLongitude[keep]
            } else if ("Lat" %in% names(metadata)) {
              df$latitude[l] <- metadata$Lat[keep]
              df$longitude[l] <- metadata$Long[keep]
            } else if ('latitudeMinutes' %in% names(metadata)) {
              df$latitude[l] <- metadata$latitudeDegrees[keep] + metadata$latitudeMinutes[keep] / 60
              df$longitude[l] <- metadata$longitudeDegrees[keep] + metadata$longitudeMinutes[keep] / 60
            } else if ('latitude' %in% names(metadata)) {
              df$latitude[l] <- metadata$latitude[keep]
              df$longitude[l] <- metadata$longitude[keep]
              } else {
              message("This is browser 3")

              browser(3)
              }




            ACTUAL_DATA <- data[[df$ID[l]]]



            # NOT CONSISTENT NAMING (v6 NJ)

            if (!("Species" %in% names(data))) {
              names(data)[which(names(data) == "species")] <- "Species"

              if (!("Species" %in% names(data))) {
                if ("V6" %in% names(data)) {
                names(data)[which(names(data) == "V6")] <- "Species"
                } else if ("X6" %in% names(data)) {
                  names(data)[which(names(data) == "X6")] <- "Species"

                }
              }

              if (!("Species" %in% names(data))) {
                message("This is browser 4")

                browser(4)
              }
            }
            df$species_richness[l] <- length(unique(data$Species[which(!(ACTUAL_DATA == 0))]))
            #df$method[l] <- sub(".*eDNA-for-MPAs/data/[^/]+/[^/]+/([^/]+).*", "\\1", name_of_data)
            df$method[l] <- sub(".*data/[^/]+/[^/]+/([^/]+).*", "\\1", name_of_data)
            if (!(names(grouped[i]) == "2025RVsurvey")) {
              df$location[l] <- location[j]
            }

            species_and_abundance <- data[, c("Species", df$ID[l]), drop = FALSE]

            species_unique <- species_and_abundance %>%
              group_by(Species) %>%
              summarise(Abundance = sum(.data[[df$ID[l]]]), .groups = "drop") %>%
              filter(Abundance > 0)

            if (nrow(species_unique) > 0) {
              df$species[l] <- paste0(species_unique$Species, collapse=', ')
              df$abundance[l] <- paste0(species_unique$Abundance, collapse=', ')
            }




            ## and add everything to main mega table.
            ## tweak formatting of . - _


          } else {
            message("This is browser 5")

            browser(5)
          }

        }

        big_df[[counter]] <- df
        counter <- counter + 1

      }
    }
  }

  final_df <- do.call(rbind, big_df)
  final_df$latitude <- round(as.numeric(final_df$latitude), 2)
  final_df$longitude <- round(as.numeric(final_df$longitude), 2)


  b1 <- which(is.na(final_df$latitude))
  b2 <- which(is.na(final_df$longitude))

  final_df <- final_df[-intersect(b1,b2),]
  final_df$year <- as.numeric(format(final_df$date, "%Y"))

  ## INCONSISTENT: SOME LONGITUDES ARE IN THE POSITIVES - NJ

  final_df$longitude[which(final_df$longitude > 0)] <- final_df$longitude[which(final_df$longitude > 0)]*-1

  # leaflet() %>%
  #   addTiles() %>%
  #   addCircleMarkers(
  #     lat = final_df$latitude,
  #     lng = final_df$longitude,
  #     popup = paste0("Lat: ", final_df$latitude,
  #                    "<br>Lon: ", final_df$longitude)
  #   )

  return(final_df)



}
